---
title: "ifc_qaqc"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),Sys.Date(),'.html')) })

output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: false
    number_sections: true
    highlight: pygments 
    theme: cosmo
    code_folding: hide
    
---

# Import and check UPAS data

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
email = 1
local_tz = "Asia/Dhaka"
source('r_scripts/load.R') #libraries
source('r_scripts/UPAS_functions.R') #functions to clean, plot, summarize
source('r_scripts/lascar_functions.R')

sample_duration_thresholds = c(1296,1584)

```

# Cleaning rules
* fill in

# Load UPAS data
``` {r load-data, cache = TRUE}

# UPAS data import and check
upasfilepath <- "~/Dropbox/IFC Sistema Field Folder/Field Data"

file_list_upas <- list.files(upasfilepath, pattern='.txt|.TXT', full.names = T,recursive = T) %>% 
  grep("DIAGNOSTIC", ., ignore.case = TRUE, value = TRUE, invert = TRUE)  

#Get rid of test files
file_list_upas = file_list_upas[sapply(file_list_upas, file.size) > 5000]

upas_header <- rbindlist(lapply(file_list_upas,read_upas_header)) %>% 
  as.data.frame() %>% 
  dplyr::arrange(UPASlogFilename,StartDateTimeUTC) %>% 
  dplyr::mutate(file_start_date = as.Date(StartDateTimeUTC),
                CartridgeID = toupper(CartridgeID),
                StartDateTimeLocal = with_tz(StartDateTimeUTC, 
                                             tzone=local_tz),
                date_start = date(StartDateTimeLocal)) %>%
  dplyr::select(-UPASfirmware,-LifetimeSampleCount,-LifetimeSampleRuntime,-GPSUTCOffset,ProgrammedStartDelay,-AppLock,-AppVersion,
                -StartOnNextPowerUp,-LogInterval,-LogFileMode,-file_start_date,-DutyCycleWindow,-GPSEnabled,-ProgrammedStartDelay,
                -StartBatteryCharge,-EndBatteryCharge,-ShutdownMode,-SampledRuntime,-VolumetricFlowRate,-FlowOffset)

DT::datatable(upas_header,caption = "UPAS summary data")
```

# Import ODK
* Survey import
* Instrument start import
*
```{r import_odk}

# ruODK user using OData service URL, username (an email), and password
# To set your username and password in the environment use these commands:
# Sys.setenv(ODKC_PW = "yourpassword")
# Sys.setenv(ODKC_UN = "yourusername")

ruODK::ru_setup(
  svc = "https://berkeleyair.getodk.cloud/v1/projects/1/forms/IFC_HouseholdSurvey_CONTROL.svc", 
  un = Sys.getenv("ODKC_UN"), 
  pw = Sys.getenv("ODKC_PW"),
  tz = "America/Denver",
  verbose = TRUE
)
odk_hhSurvey_control = lapply(ruODK::submission_get(submission_list()$instance_id),
                              function(df) df %>%
                                rbindlist(fill=T)  %>% 
                                fill(names(.),.direction="downup") %>% 
                                distinct()) %>% rbindlist(fill=TRUE)
kable(odk_hhSurvey_control,"pipe",digits = 2,title = "HH Survey; Control")





ruODK::ru_setup(svc = "https://berkeleyair.getodk.cloud/v1/projects/1/forms/IFC_HouseholdSurvey_INTER.svc")
odk_hhSurvey_inter =  lapply(ruODK::submission_get(submission_list()$instance_id),
                              function(df) df %>%
                                rbindlist(fill=T)  %>% 
                                fill(names(.),.direction="downup") %>% 
                                distinct()) %>% rbindlist(fill=TRUE)
kable(odk_hhSurvey_inter,"pipe",digits = 2,title = "HH Survey; Intervention")

ruODK::ru_setup(svc = "https://berkeleyair.getodk.cloud/v1/projects/1/forms/IFC_InstrumentEnd.svc")
odk_instrument_end =  lapply(ruODK::submission_get(submission_list()$instance_id),
                              function(df) df %>%
                                rbindlist(fill=T)  %>% 
                                fill(names(.),.direction="downup") %>% 
                                distinct()) %>% rbindlist(fill=TRUE)
kable(odk_instrument_end,"pipe",digits = 2,title = "Instrument End")

ruODK::ru_setup(svc = "https://berkeleyair.getodk.cloud/v1/projects/1/forms/IFC_InstrumentStart.svc")
odk_instrument_start =  lapply(ruODK::submission_get(submission_list()$instance_id),
                              function(df) df %>%
                                rbindlist(fill=T)  %>% 
                                fill(names(.),.direction="downup") %>% 
                                distinct()) %>% rbindlist(fill=TRUE)
kable(odk_instrument_start,"pipe",digits = 2,title = "Instrument Start")

ruODK::ru_setup(svc = "https://berkeleyair.getodk.cloud/v1/projects/1/forms/IFC_Screening_biogas.svc")
odk_screening_inter =  lapply(ruODK::submission_get(submission_list()$instance_id),
                              function(df) df %>%
                                rbindlist(fill=T)  %>% 
                                fill(names(.),.direction="downup") %>% 
                                distinct()) %>% rbindlist(fill=TRUE)
kable(odk_screening_inter,"pipe",digits = 2,title = "Screening: Intervention")

ruODK::ru_setup(svc = "https://berkeleyair.getodk.cloud/v1/projects/1/forms/IFC_Screening_control.svc")
odk_screening_control =  lapply(ruODK::submission_get(submission_list()$instance_id),
                              function(df) df %>%
                                rbindlist(fill=T)  %>% 
                                fill(names(.),.direction="downup") %>% 
                                distinct()) %>% rbindlist(fill=TRUE)
kable(odk_screening_control,"pipe",digits = 2,title = "Screening; Control")


# Review settings
# ruODK::ru_settings()
# ruODK::project_detail()
# ruODK::form_detail()



```

# Merge ODK and UPAS
```{r merge_odk_upas}




```